  CREATE TABLE "XXSMAS_SHEET11_DTLS_TB" 
   (	"TYPE" NUMBER, 
	"LEDGER_NAME" VARCHAR2(30 BYTE), 
	"LEDGER_CALENDAR" VARCHAR2(15 BYTE), 
	"PERIOD_NAME" VARCHAR2(15 BYTE), 
	"PERIOD_NUMBER" NUMBER(22,0), 
	"PERIOD_YEAR" VARCHAR2(25 BYTE), 
	"LOCATION" VARCHAR2(25 BYTE), 
	"LOCATION_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"ASSET" VARCHAR2(25 BYTE), 
	"ASSET_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"ACCOUNT" VARCHAR2(25 BYTE), 
	"ACCOUNT_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(240 BYTE), 
	"OPENING_BALANCE" NUMBER, 
	"DEBIT" NUMBER, 
	"CREDIT" NUMBER, 
	"NET_MOVEMENT" NUMBER, 
	"CLOSING_BALANCE" NUMBER, 
	"REMARKS" VARCHAR2(4000 BYTE), 
	"INSTA_LR" VARCHAR2(4000 BYTE), 
	"INSTA_FMS" VARCHAR2(4000 BYTE), 
	"RV_TYPE" VARCHAR2(4000 BYTE), 
	"VECHILE_NO" VARCHAR2(4000 BYTE), 
	"BILLING_TYPE" VARCHAR2(4000 BYTE), 
	"RENTAL_CATEGORY" VARCHAR2(4000 BYTE), 
	"CONTRACT_START_DATE" VARCHAR2(4000 BYTE), 
	"CONTRACT_END_DATE" VARCHAR2(4000 BYTE), 
	"VARIANT_NAME" VARCHAR2(4000 BYTE), 
	"ASSET_STATUS" VARCHAR2(4000 BYTE), 
	"SOLD_MONTH" VARCHAR2(4000 BYTE),
	   	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER
   );
   

   
CREATE  INDEX XXSMA_SHEET11_TB_INDEX1 ON xxsmas_sheet11_dtls_tb (ledger_name);   
CREATE  INDEX XXSMA_SHEET11_TB_INDEX2 ON xxsmas_sheet11_dtls_tb (period_name);  
CREATE  INDEX XXSMA_SHEET11_TB_INDEX3 ON xxsmas_sheet11_dtls_tb (asset);   
CREATE  INDEX XXSMA_SHEET11_TB_INDEX4 ON xxsmas_sheet11_dtls_tb (TYPE);  
