  CREATE TABLE "APPS"."XXSMAS_SUMMARY_DTLS_TB" 
   (	"TYPE" NUMBER(22,0), 
	"LEDGER_NAME" VARCHAR2(30 BYTE), 
	"LEDGER_CALENDAR" VARCHAR2(15 BYTE), 
	"PERIOD_NAME" VARCHAR2(15 BYTE), 
	"PERIOD_NUMBER" NUMBER(22,0), 
	"PERIOD_YEAR" VARCHAR2(25 BYTE), 
	"ACCOUNT" VARCHAR2(25 BYTE), 
	"ACCOUNT_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"OPENING_BALANCE" NUMBER, 
	"DEBIT" NUMBER, 
	"CREDIT" NUMBER, 
	"NET_MOVEMENT" NUMBER, 
	"CLOSING_BALANCE" NUMBER
   );
   
   
CREATE INDEX XXSMAS_SUMMARY_INDEX1 ON XXSMAS_SUMMARY_DTLS_TB  (TYPE);
CREATE INDEX XXSMAS_SUMMARY_INDEX2 ON XXSMAS_SUMMARY_DTLS_TB  (ACCOUNT);
CREATE INDEX XXSMAS_SUMMARY_INDEX3 ON XXSMAS_SUMMARY_DTLS_TB  (PERIOD_NAME);
